variables:
  GIT_STRATEGY: clone

ref-accept-k:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/ref-wrapper.sh
  artifacts:
    paths:
      - "log.*"
      - "refine-*.tar.gz"
    expire_in: 1 week

pro-accept-k:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/pro-wrapper.sh
  artifacts:
    paths:
      - "log.*"
      - "CodeCoverageReport.tar.gz"
    expire_in: 1 week

s2s-accept-k:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/s2s-wrapper.sh
  artifacts:
    paths:
      - "log-*"
    expire_in: 1 week

merge-boot-accept-k:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/boot-wrapper.sh
  artifacts:
    paths:
      - "log-*"
    expire_in: 1 week

merge-cmake-accept-k:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/cmake-wrapper.sh
  artifacts:
    paths:
      - "log-*"
    expire_in: 1 week

master-boot-accept-k:
  only:
    - master
  when: manual
  tags:
    - gitlab_runner
  script: ./acceptance/boot-wrapper.sh
  artifacts:
    paths:
      - "log-*"
    expire_in: 1 week

.cmb-accept-cmb20:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/cmb-wrapper.sh
  artifacts:
    paths:
      - "log.*"
      - "refine-*.tar.gz"
    expire_in: 1 week

