variables:
  GIT_STRATEGY: clone

ref-accept-k:
  when:
    - manual
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/ref-wrapper.sh
  artifacts:
    paths:
      - "log.*"
      - "refine-*.tar.gz"
    expire_in: 1 week

c2s-accept-k:
  when:
    - manual
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/c2s-wrapper.sh
  artifacts:
    paths:
      - "log-*"
    expire_in: 1 week

boot-accept-k:
  when:
    - manual
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/boot-wrapper.sh
  artifacts:
    paths:
      - "log-*"
    expire_in: 1 week

.cmb-accept-cmb20:
  when:
    - manual
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/cmb-wrapper.sh
  artifacts:
    paths:
      - "log.*"
      - "refine-*.tar.gz"
    expire_in: 1 week

