variables:
  GIT_STRATEGY: clone

.ref-accept-k:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/ref-wrapper.sh
  artifacts:
    paths:
      - "log.*"
      - "refine-*.tar.gz"
    expire_in: 1 week

.c2s-accept-k:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/c2s-wrapper.sh
  artifacts:
    paths:
      - "log-*"
    expire_in: 1 week

cmb-accept-cmb20:
  only:
    - merge_requests
  tags:
    - gitlab_runner
  script: ./acceptance/cmb-wrapper.sh
  artifacts:
    paths:
      - "log-*"
    expire_in: 1 week

